### ISSUE TITLE
DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API

### ISSUE THREAD

**Issue by webdiscus** [plentymarkets/feedback-plugin#151]
Output in console the deprecation warning by build process `npm run build:prod`:

```
webpack-fix-style-only-entries: removing js from style only module: main.js
(node:18462) [DEP_WEBPACK_CHUNK_ENTRY_MODULE] DeprecationWarning: Chunk.entryModule: Use new ChunkGraph API
(node:18462) [DEP_WEBPACK_MODULE_INDEX] DeprecationWarning: Module.index: Use new ModuleGraph API
(node:18462) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'filter' is deprecated)
```

Used plugin [webpack-fix-style-only-entries](https://www.npmjs.com/package/webpack-fix-style-only-entries) in not compatible with `Webpack 5`.
Instead of the `webpack-fix-style-only-entries` should be used the fork [webpack-remove-empty-scripts](https://www.npmjs.com/package/webpack-remove-empty-scripts) compatible with `Webpack 5`. This plugin work very well with Webpack 5 and has some improvements. 
In your package.json is used the Webpack 5.1.1 This plugin recommend using Webpack version >= 5.32.

To fix the warning:

[package.json](https://github.com/plentymarkets/feedback-plugin/blob/7f091ab1bb3f3a15b47598bd26ef9090a13e6356/package.json)
```js
"webpack": "^5.1.1", --> update to latest version ^5.69.1 or to at least ^5.32.0
- "webpack-fix-style-only-entries": "^0.6.0",
+ "webpack-remove-empty-scripts": "^0.7.3", 
```

[styles.config.js](https://github.com/plentymarkets/feedback-plugin/blob/master/tools/webpack/styles.config.js)
```js
- const FixStyleOnlyEntriesPlugin = require("webpack-fix-style-only-entries");
+ const RemoveEmptyScripts = require('webpack-remove-empty-scripts');
...
plugins: [
- new FixStyleOnlyEntriesPlugin(),
+ new RemoveEmptyScripts()
...
],

```

**Comment by stentrop** [comment]
Thx for the information.
